### ISSUE TITLE
BUG: os10_config not respecting dir_path or filename

### ISSUE THREAD

**Issue by tstrupp** [ansible-collections/dellemc.os10#102]
```
# EXAMPLE PLAYBOOK
---
- name: Pull Config Files
  hosts: localhost
  vars:
    provider:
      host: 1.1.1.1
      username: ~
      password: ~
  tasks:
    - name: os10 backup
      dellemc.o10.os10_config:
        provider: "{{ provider }}"
        backup: yes
        backup_options:
          dir_path: /Users/testing
```

Expected result is to save the file under "/users/testing" however the job creates a "backup" folder and dumps the filename in there.  OS9_config module works fine and respects directory_path and filename appropriately.  

os9:

    candidate = get_candidate(module)

    if module.params['backup']:
        if not module.check_mode:
            result['__backup__'] = get_config(module)
    commands = list()

os10:

    if module.params['backup']:
        if not module.check_mode:
            result['__backup__'] = get_config(module)

    commands = list()
    candidate = get_candidate(module)

**Comment by zerwes** [comment]
see #113 : it seems the config is not saved at all

**Comment by prasadapr** [comment]
As mentioned by `@zerwes` the issue is similar/dup of issue#113 or vice versa.

`@tstrupp`, yes as per the expected result, its save the file under "/users/testing" and its working  as per the expected. 
Already provided all the details and execution logs part of issue#113.

Find all the details again for this issue#102, for reference:



root@UBUNTU18-VM-38-024:~/os10_collections# cat os10_config_backup_Issue-102.yaml

```
---
- name: Pull Config Files
  hosts: spine3
  gather_facts: false
  connection: network_cli
  collections:
   - dellemc.os10

  vars:
   provider:
     host: 1.1.1.1
     username: ~
     password: ~

  tasks:
   - name: os10 backup
     os10_config:
       provider: "{{ provider }}"
       backup: yes
       backup_options:
         dir_path: /Users/testing
```
