### ISSUE TITLE
os10_interface does not provide for setting individual flowcontrol modes

### ISSUE THREAD

**Issue by G3rmN3rd** [ansible-collections/dellemc.os10#111]
##### SUMMARY
When using the os10_interface role, the flowcontrol.mode does not adhere to YAML syntax rules if you need to configure differing flow control modes. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os10_interface role

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /home/khydock/code/vxrail-cluster-1/ansible.cfg
  configured module search path = ['/home/khydock/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

##### COLLECTION VERSION

```
khydock@autolinux4:~/code/vxrail-cluster-1$ sudo ansible-galaxy collection list dellemc.os10
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
khydock@autolinux4:~/code/vxrail-cluster-1$ sudo ansible-galaxy collection install dellemc.os10
Process install dependency map
Starting collection install process
Installing 'dellemc.os10:1.1.1' to '/root/.ansible/collections/ansible_collections/dellemc/os10'
Installing 'ansible.netcommon:2.5.0' to '/root/.ansible/collections/ansible_collections/ansible/netcommon'
Installing 'ansible.utils:2.4.3' to '/root/.ansible/collections/ansible_collections/ansible/utils'
```

##### CONFIGURATION

```
khydock@autolinux4:~/code/vxrail-cluster-1$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/khydock/code/vxrail-cluster-1/ansible.cfg) = ['/home/khydock/code/vxrail-cluster-1/hosts']
NETWORK_GROUP_MODULES(/home/khydock/code/vxrail-cluster-1/ansible.cfg) = ['os10']
```

##### OS / ENVIRONMENT

Dell S5348F-ON, OS10 v10.5.2.

##### STEPS TO REPRODUCE

*[Project Directory]*
```
khydock@autolinux4:~/code/vxrail-cluster-1$ tree ./
./
├── ansible.cfg
├── archive
├── backup
├── hosts
├── host_vars
│   └── SW-07-VX-01.yml
├── README.md
├── temp
└── vxleaf-setup.yml
```
*[hosts]*
```
[all]
SW-07-VX-01 ansible_host=172.32.100.50
SW-07-VX-02 ansible_host=172.32.100.51
[vxleafs]
SW-07-VX-01
```
*[vxleaf-setup.yml]*
```
---
- hosts: vxleafs
  gather_facts: True
  connection: network_cli
  collections:
    - dellemc.os10
  roles:
#    - dellemc.os10.os10_system
#    - dellemc.os10.os10_vlan
    - dellemc.os10.os10_interface
#  tasks:
...
```

*[host_vars file Try 1]*
```
---
hostname: SW-07-VX-01
ansible_become: yes
ansible_become_method: enable
ansible_network_os: dellemc.os10.os10
build_dir: /home/khydock/code/vxrail-cluster-1/temp
os10_system:
  hostname: SW-07-VX-01

os10_vlan:
    vlan 340:
      description: Server Network
      tagged_members:
        - port: ethernet 1/1/1
          state: present
        - port: ethernet 1/1/2
          state: present
        - port: ethernet 1/1/3
          state: present
        - port: ethernet 1/1/4
        
os10_interface:
  ethernet 1/1/1:
    desc: 07-VX-01 Server Network Primary
    switchport: true
    portmode: trunk
    flowcontrol:
      state: "present"
      mode: "receive"
      enable: "off"
    flowcontrol:
      state: "present"
      mode: "transmit"
      enable: "on"
    admin: "up"
...
```
I have also tried:
*[host_vars file Try 2]*
```
---
hostname: SW-07-VX-01
ansible_become: yes
ansible_become_method: enable
ansible_network_os: dellemc.os10.os10
build_dir: /home/khydock/code/vxrail-cluster-1/temp
os10_system:
  hostname: SW-07-VX-01

os10_vlan:
    vlan 340:
      description: Server Network
      tagged_members:
        - port: ethernet 1/1/1
          state: present
        - port: ethernet 1/1/2
          state: present
        - port: ethernet 1/1/3
          state: present
        - port: ethernet 1/1/4
        
os10_interface:
  ethernet 1/1/1:
    desc: 07-VX-01 Server Network Primary
    switchport: true
    portmode: trunk
    flowcontrol:
      - mode: "receive"
        enable: "off"
        state: present
      - mode: "transmit"
        enable: "on"
        state: present
    admin: "up"
```
*[With host_vars file Try 1]*
```
khydock@autolinux4:~/code/vxrail-cluster-1$ ansible-playbook -i ./hosts vxleaf-setup.yml

PLAY [vxleafs] **************************************************************************************************************************************************************************
[WARNING]: While constructing a mapping from /home/khydock/code/vxrail-cluster-1/host_vars/SW-07-VX-01.yml, line 24, column 5, found a duplicate dict key (flowcontrol). Using last
defined value only.

TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [SW-07-VX-01]

TASK [os10_interface : Generating interface configuration for os10] *********************************************************************************************************************
skipping: [SW-07-VX-01]

TASK [os10_interface : Provisioning interface configuration for os10] *******************************************************************************************************************
ok: [SW-07-VX-01]

PLAY RECAP ******************************************************************************************************************************************************************************
SW-07-VX-01                : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

*[With host_vars file Try 2]*
```
khydock@autolinux4:~/code/vxrail-cluster-1$ ansible-playbook -i ./hosts vxleaf-setup.yml

PLAY [vxleafs] **************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [SW-07-VX-01]

TASK [os10_interface : Generating interface configuration for os10] *********************************************************************************************************************
skipping: [SW-07-VX-01]

TASK [os10_interface : Provisioning interface configuration for os10] *******************************************************************************************************************
ok: [SW-07-VX-01]

PLAY RECAP ******************************************************************************************************************************************************************************
SW-07-VX-01                : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0  
```
##### EXPECTED RESULTS

```
SW-07-VX-01# show running-configuration | find ethernet1/1/1
interface ethernet1/1/1
 description "07-VX-01 Server Network Primary"
 no shutdown
 switchport mode trunk
 switchport access vlan 1
 switchport trunk allowed vlan 340
 flowcontrol receive off
 flowcontrol transmit on
!
```
##### ACTUAL RESULTS

```
SW-07-VX-01# show running-configuration | find ethernet1/1/1
interface ethernet1/1/1
 description "07-VX-01 Server Network Primary"
 no shutdown
 switchport mode trunk
 switchport access vlan 1
 switchport trunk allowed vlan 340
 flowcontrol receive on
 flowcontrol transmit on
!
```

```paste below

```

**Comment by G3rmN3rd** [comment]
##### Update:

Granted the issue can be rectified via a direct task overwrite using *os10_config*:
[*Updated vxleaf-setup.yml*]
```
---
- hosts: vxleafs
  gather_facts: True
  connection: network_cli
  collections:
    - dellemc.os10
  roles:
#    - dellemc.os10.os10_system
#    - dellemc.os10.os10_vlan
    - dellemc.os10.os10_interface
  tasks:
    - name: Flowcontrol ethernet 1/1/1
      os10_config:
        lines:
          - flowcontrol receive on
          - flowcontrol transmit off
        before: ['interface ethernet 1/1/1']

    - name: Flowcontrol ethernet 1/1/2
      os10_config:  
        lines:
          - flowcontrol receive on
          - flowcontrol transmit off
        before: ['interface ethernet 1/1/2']

    - name: Flowcontrol ethernet 1/1/3
      os10_config:  
        lines:
          - flowcontrol receive on
          - flowcontrol transmit off
        before: ['interface ethernet 1/1/3']

    - name: Flowcontrol ethernet 1/1/4
      os10_config:  
        lines:
          - flowcontrol receive on
          - flowcontrol transmit off
        before: ['interface ethernet 1/1/4']
...
```

However this workaround makes the playbook less scale-able for larger operations involving leaf-spine architecture. I still consider updating the role to allow for flow control multi-line variance, value-added work.

**Comment by prasadapr** [comment]
@G3rmN3rd, thanks for the complete details.
As you mentioned above we can directly overwrite the configuration using os10_config:

we can achieve the good scale-able for larger operations using the below playbook.
`we no need to configure flow control for each interface one by one. In one shot we can configure flow control for all/multiple interfaces.`

Find the playbook for the reference:

root@UBUNTU18-VM-38-024:~/os10_collections# cat OS10_flowcontromodes_issue-111.yaml
```
---
- hosts: datacenter
  gather_facts: true
  connection: network_cli
  collections:
   - dellemc.os10

  tasks:
    - name: create vlan 340
      os10_config:
         lines:
          - interface vlan 340

    - name: configure Flowcontrol for ethernet 1/1/1-1/1/3
      os10_config:
         lines:
          - interface range ethernet 1/1/1-1/1/3
          - no shutdown
          - switchport mode trunk
          - switchport trunk allowed vlan 340
          - flowcontrol receive off
          - flowcontrol transmit on

    - name: configure Flowcontrol for ethernet 1/1/4-1/1/6
      os10_config:
         lines:
          - interface range ethernet 1/1/4-1/1/6
          - no shutdown
          - switchport mode trunk
          - switchport trunk allowed vlan 340
          - flowcontrol receive on
          - flowcontrol transmit on

```
