### ISSUE TITLE
PR #144 breaks prompt/answer in os10_command module

### ISSUE THREAD

**Issue by lucastobey** [ansible-collections/dellemc.os10#149]
##### SUMMARY
PR #144 breaks command/prompt/answer function of os10_command module. This seems to be due to the change to expect the commands to all be strings. This breaks the dictionary k:v expectation from the command/prompt/answer feature in the module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[os10_command.py
](https://github.com/ansible-collections/dellemc.os10/blob/master/plugins/modules/os10_command.py)
##### ANSIBLE VERSION

```
ansible [core 2.15.4]
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION
latest master branch pulled from this repo

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
Use the command/prompt/answer syntax to run against something

```yaml
---
- name: TEST
  hosts: all    
  tasks:

    - name: TEST
      dellemc.os10.os10_command:
        commands:
          - command: 'reload'
            prompt: 'Proceed to reboot'
            answer: 'n'
```

##### EXPECTED RESULTS
The module to work through the command, then prompt, then answer. Because of the changes in PR #144 to the os10_command module, the module now sees the `command: 'reload'` line as a string instead of a dictionary.

##### ACTUAL RESULTS

```paste below
fatal: [swxx]: FAILED! => {"changed": false, "msg": "{'command': 'reload', 'prompt': 'Proceed to reb\u001bEoot', 'answer': 'n'}\r\n% Error: Unrecognized command.\r\n\u0007swxx# ", "rc": -32603}

```
