### ISSUE TITLE
os10_static_route role

### ISSUE THREAD

**Issue by bas-1988** [ansible-collections/dellemc.os10#163]
We are really wanting to have a role for static route's.

e.g.
```
os10_static_route:
  routes:   
    - route: 1.1.1.0/24
      gateway: 10.1.1.1
      state: present
  vrf: 
    name: "xxx"
    routes:
      - route: 2.2.2.0/24
        gateway: 20.1.1.1
        state: present
```

```
{% if os10_static_route is defined and os10_static_route %}
  {% for staticroute in os10_static_route.routes %}
        {% if staticroute.route is defined and staticroute.route %}
          {% if staticroute.state is defined and staticroute.state == "absent" %}
no ip route {{ staticroute.route }} {{ staticroute.gateway }}
          {% else %}
ip route {{ staticroute.route }} {{ staticroute.gateway }}
          {% endif %}
        {% endif %}
  {% for vrfstaticroute in os10_static_route.vrf.routes %}
      {% if vrfstaticroute.route is defined and vrfstaticroute.route %}
          {% if vrfstaticroute.state is defined and vrfstaticroute.state == "absent" %}
no ip route vrf {{ os10_static_route.vrf.name }} {{ vrfstaticroute.route }} {{ vrfstaticroute.gateway }}
          {% else %}
ip route vrf {{ os10_static_route.vrf.name }} {{ vrfstaticroute.route }} {{ vrfstaticroute.gateway }}
          {% endif %}
        {% endif %}
      {% endfor %}
```

Could you please create something like this
