### ISSUE TITLE
Get facts not returning interfaces data

### ISSUE THREAD

**Issue by rfreddy** [ansible-collections/dellemc.os10#166]
##### SUMMARY

When getting facts from OS10 devices some fields come empty, specifically ansible_net_interfaces 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

.ansible/collections/ansible_collections/dellemc/os10/plugins/modules/os10_facts.py
##### ANSIBLE VERSION

```ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rfreddy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/rfreddy/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```# /home/rfreddy/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     2.6.1
ansible.utils         2.6.1
community.general     5.4.0
community.network     5.0.2
dellemc.os10          1.2.0
dellemc.os6           1.0.7
dellemc.os9           1.0.4
juniper.device        1.0.2
junipernetworks.junos 4.1.0
netbox.netbox         3.11.0
```

##### CONFIGURATION

```CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /home/.super_secret_vault
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Host: Ubuntu 22.04

Switch: Dell N3048-ON
OS 10 Version 10.5.3.4

##### STEPS TO REPRODUCE

ansible-playbook -i inventory.yaml  get_fact_os10.yaml

```yaml
Playbook: get_fact_os10.yaml:
---
- hosts: [dellos]
  connection: network_cli
  collections:
    - dellemc.os10
  gather_facts: yes

  vars:
    target_dir: "/home/rfreddy/ansible/facts"

  tasks:
   - name: Include secrets and vars
     include_vars: dell_vars.yml

   - name: "Gather Dell EMC OS10 Device Facts"
     os10_facts:
       gather_subset: interfaces
     register: facts
    
   - name: "Writing Facts for Dell EMC OS10 Device"
     lineinfile:
         path: "{{ target_dir }}/{{ ansible_net_hostname }}_facts.txt"
         line: "{{ facts }}"
         create: true
```

##### EXPECTED RESULTS

For OS9 facts the data returned for the interfaces looks like this

'ansible_net_interfaces': {'GigabitEthernet 1/1': {'
description': None, 'macaddress': '8c:47:be:64:8a:82', 'ipv4': None, 'mtu': 1554, 'bandwidth': 1000, 'mediatype': None, 'duplex': 'full
', 'lineprotocol': 'up', 'operstatus': 'up', 'type': 'DellEth'}

##### ACTUAL RESULTS

```For OS10 the same field comes like this

'ansible_net_interfaces': {}

```
