### ISSUE TITLE
DellOS10_Facts: ansible_net_config is empty/"None"

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/dellemc.os10#23]
_From @Solace7 on Jun 24, 2020 23:27_

##### SUMMARY
ansible_net_config variable is not showing running configuration

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dellos10_facts

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Host OS: CentOS 07 VM (ESXi )
Python version: 2.7.5

Tested On:
Two Dell MX9116n running Dell OS 10.5.0.2.468

##### STEPS TO REPRODUCE

Run playbook to gather dellos10_facts. 

```yaml
 gather_facts: yes
  connection: network_cli
  vars:
      ansible_network_os: 'dellos10'
      ansible_ssh_user: 'swadmin'
      ansible_ssh_pass: '********'
  tasks:
    - name: get configuration
      dellos10_facts:
        gather_subset:
          - config
      register: facts
    - name: Debug
      debug:
        msg: "{{ facts }}"
```

##### EXPECTED RESULTS

Expected facts.ansible_facts.ansible_net_config to show running-configuration

##### ACTUAL RESULTS

ansible_net_config has value of "None" or ""

```
ok: [192.168.161.251] => {
    "msg": {
        "ansible_facts": {
            "ansible_net_config": "",
            "ansible_net_gather_subset": [
                "default",
                "config"
            ],
            "ansible_net_hostname": "win-tx-sw-core01",
            "ansible_net_model": "MX9116N-ON",
            "ansible_net_name": "Enterprise",
            "ansible_net_servicetag": "B527Z23",
            "ansible_net_version": "10.5.0.2"
        },
        "changed": false,
        "failed": false
    }
}
ok: [192.168.161.252] => {
    "msg": {
        "ansible_facts": {
            "ansible_net_config": "None",
            "ansible_net_gather_subset": [
                "default",
                "config"
            ],
            "ansible_net_hostname": "win-tx-sw-core02",
            "ansible_net_model": "MX9116N-ON",
            "ansible_net_name": "Enterprise",
            "ansible_net_servicetag": "8LT1Z23",
            "ansible_net_version": "10.5.0.2"
        },
        "changed": false,
        "failed": false
    }
}
```

_Copied from original issue: ansible/ansible#70282_
