### ISSUE TITLE
Templates not evaluating with os10_config

### ISSUE THREAD

**Issue by zjpeterson** [ansible-collections/dellemc.os10#31]
##### SUMMARY
Any configuration template passed using the `src` parameter of `os10_config` seems not to result in the template being evaluated. Rather, the name of the template file appears to be sent to the switch as a command.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os10_config

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
# show version 
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2019 by Dell Inc. All Rights Reserved.
OS Version: 10.5.0.1P1
Build Version: 10.5.0.1P1.433
Build Time: 2019-09-16T22:01:53+0000
System Type: S5232F-ON
Architecture: x86_64
```

##### STEPS TO REPRODUCE

my_template.j2:
```yaml
snmp-server community dellemc ro
```
my_playbook.yml
```yaml
---
- name: Configure switches
  hosts: leaf1
  connection: network_cli
  gather_facts: no

  collections:
    - dellemc.os10

  tasks:
    - name: Create VLANs
      os10_config:
        src: my_template.j2
```

##### EXPECTED RESULTS

The configuration `snmp-server community dellemc ro` is pushed to the switch

##### ACTUAL RESULTS

```paste below
fatal: [leaf1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "command": "my_template.j2", "msg": "my_template.j2\r\n% Error: Unrecognized command.\r\n\u0007leaf1(config)# ", "rc": -32603}

```

Of note: If my task instead looks like the following:
```yaml
    - name: Create VLANs
      os10_config:
        src: "{{ lookup('template', 'my_template.j2' }}"
```

This does succeed, but goes against the documented usage.
