### ISSUE TITLE
os10_vlan Error: Unrecognized command

### ISSUE THREAD

**Issue by tomminerd** [ansible-collections/dellemc.os10#40]
##### SUMMARY
When running my playbook using the os10_vlan role, I get the following output:

fatal: [U01TL1DCDSW04]: FAILED! => {
    "changed": false,
    "command": "os10_vlan.j2",
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": "os10_vlan.j2",
            "update": "merge"
        }
    },
    "msg": "os10_vlan.j2\r\n% Error: Unrecognized command.\r\n\u0007U01TL1DCDSW04(config)# ",
    "rc": -32603
}

PLAY RECAP ********************************************************************************************************************************************************************
U01TL1DCDSW04              : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module: os10_command.py
Role: dellemc.os10.os10_vlan

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]


```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/mnt/scripts/ansible/OS10_switches_dc.yml']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ADMTMinerd
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles', '/root/.ansible/collections/ansible_collections/dellemc/os10/roles']
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/vault_pass.txt
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'virtualbox', 'yaml', 'constructed']
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Switch Model: Dell EMC PowerSwitch S4048T-ON
OS: OS10 v10.5.1.4

##### STEPS TO REPRODUCE
Running Ansible on Ubuntu 20.04 LTS
1. install the os10 collection from Ansible-Galaxy.
2. Create/update inventory file.
3. Create/update group_vars file.
4. Create playbook.
5. Execute playbook against a single switch to test.

```
Playbook: OS10_switch_config.yml

---
- name: Data center switch configuration
  hosts: all
  gather_facts: no
  vars_files:
    - password.yml
  roles:
    - dellemc.os10.os10_vlan

Inventory: OS10_switches_dc.yml

---
  all:
    children:
      dellos10:
        children:
          dc_backbone:
            children:
              primary_switch:
                hosts:
                  U01DCCSW01:
                    ansible_host: 10.206.47.11
                    mgmtip: 10.206.47.11
                  U01TL1DCDSW01:
                    ansible_host: 10.206.47.13
                    mgmtip: 10.206.47.13
                  U01TL1DCDSW03:
                    ansible_host: 10.206.47.15
                    mgmtip: 10.206.47.15
                  U01TL2DCDSW01:
                    ansible_host: 10.206.47.17
                    mgmtip: 10.206.47.17
                  U01TL4DCDSW01:
                    ansible_host: 10.206.47.19
                    mgmtip: 10.206.47.19
              secondary_switch:
                hosts:
                  U01DCCSW02:
                    ansible_host: 10.206.47.12
                    mgmtip: 10.206.47.12          
                  U01TL1DCDSW02:
                    ansible_host: 10.206.47.14
                    mgmtip: 10.206.47.14          
                  U01TL1DCDSW04:
                    ansible_host: 10.206.47.16
                    mgmtip: 10.206.47.16          
                  U01TL2DCDSW02:
                    ansible_host: 10.206.47.18
                    mgmtip: 10.206.47.18          
                  U01TL4DCDSW02:
                    ansible_host: 10.206.47.20
                    mgmtip: 10.206.47.20

Vars file: group_vars/dellos10.yml

---
ansible_ssh_user: ADMTMinerd
ansible_ssh_pass: "{{ login }}"
ansible_become: yes
ansible_become_method: enable
ansible_become_password: "{{ enable }}"
ansible_network_os: dellemc.os10.os10
ansible_connection: network_cli
ansible_python_interpreter: /usr/bin/python3
os10_vlan:
    vlan 100:
      description: Blue
      state: present
    vlan 10:
      state: absent

```

##### EXPECTED RESULTS
I'm expecting the switch to have VLAN 100 added to the switch after running the following command:

ansible-playbook -i OS10_switches_dc.yml OS10_switch_config.yml -vvvv --limit U01TL1DCDSW04

##### ACTUAL RESULTS

```
root@u01devvans02:/etc/ansible# ansible-playbook -i OS10_switches_dc.yml OS10_switch_config.yml -vvvv --limit U01TL1DCDSW04 
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/OS10_switches_dc.yml as it did not pass its verify_file() method
virtualbox declined parsing /etc/ansible/OS10_switches_dc.yml as it did not pass its verify_file() method
Parsed /etc/ansible/OS10_switches_dc.yml inventory source with yaml plugin
Trying secret FileVaultSecret(filename='/etc/ansible/vault_pass.txt') for vault_id=default
Read vars_file 'password.yml'
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: OS10_switch_config.yml **********************************************************************************************************************************************
Positional arguments: OS10_switch_config.yml
verbosity: 4
remote_user: ADMTMinerd
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/OS10_switches_dc.yml',)
subset: U01TL1DCDSW04
forks: 5
1 plays in OS10_switch_config.yml
Read vars_file 'password.yml'
Read vars_file 'password.yml'
Read vars_file 'password.yml'

PLAY [Data center switch configuration] ***************************************************************************************************************************************
META: ran handlers
Read vars_file 'password.yml'

TASK [os10_vlan : Generating VLAN configuration for os10] *********************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/dellemc/os10/roles/os10_vlan/tasks/main.yml:3
skipping: [U01TL1DCDSW04] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
Read vars_file 'password.yml'

TASK [os10_vlan : Provisioning VLAN configuration for os10] *******************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/dellemc/os10/roles/os10_vlan/tasks/main.yml:11
<10.206.47.16> attempting to start connection
<10.206.47.16> using connection plugin network_cli
<10.206.47.16> local domain socket does not exist, starting it
<10.206.47.16> control socket path is /root/.ansible/pc/f897736360
<10.206.47.16> local domain socket listeners started successfully
<10.206.47.16> loaded cliconf plugin ansible_collections.dellemc.os10.plugins.cliconf.os10 from path /root/.ansible/collections/ansible_collections/dellemc/os10/plugins/cliconf/os10.py for network_os dellemc.os10.os10
<10.206.47.16> 
<10.206.47.16> local domain socket path is /root/.ansible/pc/f897736360
<10.206.47.16> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.206.47.16> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792 `" && echo ansible-tmp-1597099015.8308136-28282784995792="` echo /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/dellemc/os10/plugins/modules/os10_config.py
<10.206.47.16> PUT /root/.ansible/tmp/ansible-local-223940ywdk_tvk/tmpevpexdj0 TO /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792/AnsiballZ_os10_config.py
<10.206.47.16> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792/ /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792/AnsiballZ_os10_config.py && sleep 0'
<10.206.47.16> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792/AnsiballZ_os10_config.py && sleep 0'
<10.206.47.16> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-223940ywdk_tvk/ansible-tmp-1597099015.8308136-28282784995792/ > /dev/null 2>&1 && sleep 0'
fatal: [U01TL1DCDSW04]: FAILED! => {
    "changed": false,
    "command": "os10_vlan.j2",
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": "os10_vlan.j2",
            "update": "merge"
        }
    },
    "msg": "os10_vlan.j2\r\n% Error: Unrecognized command.\r\n\u0007U01TL1DCDSW04(config)# ",
    "rc": -32603
}

PLAY RECAP ********************************************************************************************************************************************************************
U01TL1DCDSW04              : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

```
