### ISSUE TITLE
os10_interfaces does not support S5248F-ON interface breakout

### ISSUE THREAD

**Issue by lpereira1** [ansible-collections/dellemc.os10#52]
##### SUMMARY
os10_interfaces when you use the fanout paramater uses the older command style "interface breakout 1/1/x" which does not work on the S5248F-ON on 10.5.2.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os10_interfaces

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lpereira/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lpereira/.local/lib/python3.6/site-packages/ansible
  executable location = /home/lpereira/.local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION

```
os10_interface:
   ethernet1/1/55:
        fanout: 40g-1x

```

##### OS / ENVIRONMENT
Dell S5248F-ON version 10.5.2.0

##### STEPS TO REPRODUCE
Attempted to configure the fan out the interface with the below.  I believe that in 10.5.2.0 you need to instead use the port-group command but my current workaround it to just enable the auto-breakout feature. 

```
[hostvar]
os10_interface:
   ethernet1/1/55:
        fanout: 40g-1x

---
- name: Deploy VTL Trunking to Switch
  hosts: DC
  gather_facts: False
  connection: network_cli
  collections:
    - dellemc.os10
     
  roles:
    - os10_interface

```

##### EXPECTED RESULTS
Successful fanout of interface

##### ACTUAL RESULTS

```
fatal: [DC-tor02]: FAILED! => {"changed": false, "command": "interface breakout 1/1/55 map 40g-1x", "msg": "interface breakout 1/1/55 map 40g-1x\r\n% Error: Illegal parameter.\r\n\u0007DC-TOR02(config)# ", "rc": -32603}
fatal: [DC-tor01]: FAILED! => {"changed": false, "command": "interface breakout 1/1/55 map 40g-1x", "msg": "interface breakout 1/1/55 map 40g-1x\r\n% Error: Illegal parameter.\r\n\u0007DC-TOR01(config)# ", "rc": -32603}

```

**Comment by gunasekaran-t** [comment]
@lpereira1 S52XX platform does not support interface level fanout. Fanout is done at portgroup level using port-group CLI. Currently it is not supported in any roles. You can achieve the same using os10_config module. 

```
  tasks:
    - name: port-group
      os10_config:
        lines:
          - mode eth 40g-1x
        parents: ['port-group 1/1/17']
```
