### ISSUE TITLE
Role os10_vlan fails to add port-channel port if long syntax of interface name is used

### ISSUE THREAD

**Issue by jalmargyyk** [ansible-collections/dellemc.os10#57]
##### SUMMARY

Role os10_vlan has some issues dealing with port syntax. The device (S5248F-ON) fails to parse configuration when the same port-channel is defined as tagged_member with syntax `port-channel10` to multiple vlans and one of the vlans has also untagged_members configured. 

As a workaround a shorter name (e.g. `Po10`) of the interface can be used. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

role os10_vlan

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/foobar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = [u'all']
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 10
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

# show version
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2020 by Dell Inc. All Rights Reserved.
OS Version: 10.5.2.0P1
Build Version: 10.5.2.0P1.246
Build Time: 2020-11-02T19:55:54+0000
System Type: S5248F-ON
Architecture: x86_64
Up Time: 1 week 20:31:32

##### STEPS TO REPRODUCE

Configure the same port-channel interface to multiple vlans

```yaml
os10_vlan:
  vlan 401:
    description: vlan401
    tagged_members:
      - port: port-channel10
        state: present
    state: present
  vlan 430:
    description: vlan430
    tagged_members:
      - port: port-channel10
        state: present
    untagged_members:
      - port: eth1/1/12:1
        state: present
    state: present
```

##### EXPECTED RESULTS

Vlans should be configured correctly to device.

##### ACTUAL RESULTS

```paste below
fatal: [redacted]: FAILED! => {
    "changed": false,
    "command": "switchport trunk allowed vlan 430",
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": "\n\ninterface vlan401\n description vlan401\n\n\n\n\n\ninterface port-channel10\n switchport mode trunk\n switchport trunk allowed vlan 401\n\n\n\ninterface vlan430\n description vlan430\n\n\n\n\ninterface eth1/1/12:1\n switchport access vlan 430\n\ninterface port-channel10\n switchport mode trunk\n switchport trunk allowed vlan 430\n\n",
            "update": "merge"
        }
    },
    "msg": "switchport trunk allowed vlan 430\r\n% Error: Interface cannot be an access and trunk member of the same VLAN. One of the vlan in the range provided is already an access vlan.\r\nredacted(conf-if-eth1/1/12:1)# ",
    "rc": -32603
}
```
##### WORKAROUND
This can be avoided by using shorter syntax of the Port-channel as follows:
```yaml
os10_vlan:
  vlan 401:
    description: vlan401
    state: present
    tagged_members:
      - port: Po10
        state: present
  vlan 430:
    description: vlan430
    tagged_members:
      - port: Po10
        state: present
    untagged_members:
      - port: eth1/1/12:1
        state: present
    state: present
```
##### WORKAROUND RESULTS
````
changed: [redacted] => {
    "changed": true,
    "commands": [
        "interface Po10",
        "switchport mode trunk",
        "switchport trunk allowed vlan 401",
        "interface eth1/1/12:1",
        "switchport access vlan 430",
        "interface Po10",
        "switchport mode trunk",
        "switchport trunk allowed vlan 430",
        "commit"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": "\n\ninterface vlan401\n description vlan401\n\n\n\n\n\ninterface Po10\n switchport mode trunk\n switchport trunk allowed vlan 401\n\n\n\ninterface vlan430\n description vlan430\n\n\n\n\ninterface eth1/1/12:1\n switchport access vlan 430\n\ninterface Po10\n switchport mode trunk\n switchport trunk allowed vlan 430\n\n",
            "update": "merge"
        }
    },
    "saved": false,
    "updates": [
        "interface Po10",
        "switchport mode trunk",
        "switchport trunk allowed vlan 401",
        "interface eth1/1/12:1",
        "switchport access vlan 430",
        "interface Po10",
        "switchport mode trunk",
        "switchport trunk allowed vlan 430",
        "commit"
    ]
}
```
