### ISSUE TITLE
Add support for prompt in os10_command module

### ISSUE THREAD

**Issue by TrevorSquillario** [ansible-collections/dellemc.os10#83]
##### SUMMARY

The Ansible User Guide mentions that network modules should allow automatic answering of prompts. This is generally handled by a `prompt` parameter. Does it make sense to add this to the os10_command module?

https://docs.ansible.com/ansible/latest/network/user_guide/network_working_with_command_output.html#handling-prompts-in-network-modules
https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_command_module.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

dellemc.os10.os10_command

##### ADDITIONAL INFORMATION

My use case is when deleting files. You are prompted to enter Yes or No. I'm not finding a way to do this currently. 

Current
```yaml
    - name: "Remove Support Bundle"
      dellos10_command:
        commands:
          - "delete supportbundle://sosreport-MX9116-xxxxxxxx.tar.xz"
```

Suggested
```yaml
    - name: "Remove Support Bundle"
      dellos10_command:
        commands:
          - "delete supportbundle://sosreport-MX9116-xxxxxxxx.tar.xz"
        prompt:
          - "Proceed to delete supportbundle:"
        answer:
          - "yes"
```
