### ISSUE TITLE
os10_vlan role is slow

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/dellemc.os10#90]
We have a very large VLAN & Port configuration that we push to our switches using the `os10_vlan` role. It is one of the slowest roles to execute, and we would like to investigate ways to speed it up.

The main issue appears to be the number of commands sent, and the fact that OS10 takes a lot of time to process the commands.

I have created a sample repo that demonstrates the performance of this role at https://github.com/sc68cal/dellos-vlan-perf

We have seen execution times of around two minutes, to close to three for it to complete.

**Comment by sc68cal** [comment]
The current role loops through every `vlan` defined in the YAML, and then for every port defined in the `tagged_members` and `untagged_members` attribute, emits an `interface` command that configures the port. So, for an example:

```yaml
os10_vlan:
  vlan 10:
    tagged_members:
      - port: ethernet 1/1/1
 
  vlan 11:
    tagged_members:
      - port: ethernet 1/1/1

  vlan 12:
    tagged_members:
      - port: ethernet 1/1/1
```

The current template code would end up emitting three commands:

```
interface ethernet1/1/1
 switchport trunk allowed vlan 10

interface ethernet1/1/1
 switchport trunk allowed vlan 11

interface ethernet1/1/1
 switchport trunk allowed vlan 12
```

And then it depends on DellOS to merge these config commands into something like

```
interface ethernet1/1/1
  switchport trunk allowed vlan 10,11,12
```

Perhaps there's a way to invert this behavior, where we process the VLANs, create a mapping for all the allowed VLANs that a port is supposed to allow, and emit just the last command instead of depending on the OS to merge it.
