### ISSUE TITLE
dellos10_config does not process jinja2 templates from "src"

### ISSUE THREAD

**Issue by cultcom** [ansible-collections/dellemc.os10#98]
##### SUMMARY
I try to configure a switch with a given template and all what is sent to the switch is the literal name of the file pointed to as "src".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
https://github.com/ansible-collections/dellemc.os10/blame/master/plugins/modules/os10_config.py#L221

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.5] 
  config file = /home/xxx/workdir/playbooks/dell-OS10/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
(master) xxx@vewok ~/workdir/playbooks/dell-OS10 $ pip freeze | grep ansible
ansible==4.5.0
ansible-core==2.11.5
ansible-pylibssh==0.2.0

```

##### COLLECTION VERSION
```paste below
dellemc.os10      1.1.1                                   
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(/home/xxx/workdir/playbooks/dell-OS10/ansible.cfg) = True
INTERPRETER_PYTHON(/home/xxx/workdir/playbooks/dell-OS10/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT
Controller:
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 20.2
Release:        20.2
Codename:       uma

Switch:
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2021 by Dell Inc. All Rights Reserved.
OS Version: 10.5.2.7
Build Version: 10.5.2.7.374
Build Time: 2021-07-28T04:48:16+0000
System Type: S5248F-ON
Architecture: x86_64
Up Time: 4 days 02:00:54

##### STEPS TO REPRODUCE

```yaml
---
- hosts:
    - spine
    - leaf
  gather_facts: False

  tasks:
    - name: "Provision basic settings"
      dellemc.os10.os10_config:
        src: templates/00-hrz-basics.j2
```
```
ansible-playbook -i inventory/core playbooks/basic.yml -l core-leaf-c-02

PLAY [spine,leaf] *********************************************************************************************************************

TASK [Provision basic settings] *******************************************************************************************************

fatal: [core-leaf-c-02]: FAILED! => {"changed": false, "command": "templates/00-hrz-basics.j2", "msg": "templates/00-hrz-basics.j2\r\n% Error: Unrecognized command.\r\n\u0007core-leaf-c-02(config)# ", "rc": -32603}

PLAY RECAP ****************************************************************************************************************************
core-leaf-c-02             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

##### EXPECTED RESULTS
I expect the jinja2 template to be evaluated and sent as commands to the switch.

##### ACTUAL RESULTS
The literal filename configured as "src" is sent as a command to the switch.

**Comment by lpereira1** [comment]
Im having the same issue here

**Comment by zordanda** [comment]
same issue, was working with the old ansible.builtin.dellos10

**Comment by javeedf** [comment]
Could you please check if this helps?
Run your playbook as below,

`ANSIBLE_NETWORK_GROUP_MODULES=os10 ansible-playbook -i inventory/core playbooks/basic.yml -l core-leaf-c-02`

between, is the roles working fine?

**Comment by cultcom** [comment]
No, sorry, I get the same error.

**Comment by zordanda** [comment]
same result for me. 

fatal: [PLAT-SW-1]: FAILED! => {"changed": false, "command": "templates/plat_system.j2", "msg": "plat_system.j2\r\n% Error: Unrecognized command.\r\n\u0007PLAT-SW-1(config)# ", "rc": -32603}


roles (dellemc.os10.os10_system in this case) work fine though.

**Comment by javeedf** [comment]
@zordanda Could you please paste your directory structure?

**Comment by zordanda** [comment]
just some additional info, i have a role that extends the functionalities of dellemc.os10.os10_system. 
i put this new role under ~/.ansible/roles/mysystemrole

this is the structure of the role dir:
```
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── LICENSE
├── README.md
├── tasks
│   └── main.yml
├── templates
│   └── plat_system.j2
└── vars
    └── main.yml
```

the directory where the playbook is located contains 

```
├── 1_L3Switch_conf_playbook.yaml
├── ansible.cfg
├── group_vars
│   └── L3Switch.yaml
├── hosts.yaml
├── host_vars
│   ├── PLAT-SW-1.yaml
│   ├── PLAT-SW-2.yaml
├── secrets.yaml
```

**Comment by javeedf** [comment]
@zordanda if you are creating a new role, then your playbook should look like this,

```
---
- hosts: L3Switch
  gather_facts: False
  connection: network_cli
  collections:
    - dellemc.os10  
  roles:
    - mysystemrole
```
Roles: mysystemrole/tasks/main.yaml file should look as below, **no** need to mention, templates/plat_system.j2

```
 - name: "Provisioning plat Systems config"
   dellemc.os10.os10_config:
      src: plat_system.j2
   register: output
```

if this doesn't work, if possible please share your code repo

**Comment by zordanda** [comment]
That exactly how my playbook looks like. And I removed the "templates/" part of the path from src in  mysystemrole/tasks/main.yaml but I still get the same error.
BTW thanks for your help.

**Comment by zordanda** [comment]
I tried copying the dellemc.os10.os10_system role from ~/.ansible/collections/ansible_collections/dellemc/os10/roles/os10_system to .ansible/roles/mysystem

and using the original role in the playbook works, while using the renamed one does not.

**Comment by javeedf** [comment]
@zordanda I think we are missing the meta/main.yaml file

**Comment by zordanda** [comment]
Same when using the os10_config module directly in the playbook, with the template in the same folder as the playbook.

playbook:
```
---
- hosts: L3Switch
  gather_facts: False
  connection: network_cli
  tasks:
  - name: "Provisioning system configuration for os10"
    dellemc.os10.os10_config:
      src: os10_system.j2
    register: output 
```

output:
```
fatal: [PLAT-SW-1]: FAILED! => {
    "changed": false,
    "command": "os10_system.j2",
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": "os10_system.j2",
            "update": "merge"
        }
    },
    "msg": "os10_system.j2\r\n% Error: Unrecognized command.\r\n\u0007PLAT-SW-1(config)# ",
    "rc": -32603
}
```

however, it works if I include the "collections" in the playbook as follows:
playbook:
```
---
- hosts: L3Switch
  gather_facts: False
  connection: network_cli
  collections:
  - dellemc.os10
  tasks:
  - name: "Provisioning system configuration for os10"
    os10_config:
      src: os10_system.j2
    register: output 
```

output:
```
ok: [PLAT-SW-1] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": "hostname PLAT-SW-1\n",
            "update": "merge"
        }
    },
    "saved": false
}
```

**Comment by javeedf** [comment]
@zordanda We need to create a directory like this. not sure whether this help or not.

https://github.com/ansible-collections/dellemc.os10/tree/master/roles/os10_system/meta

**Comment by cultcom** [comment]
I tried playing around with the different hints from this thread and can tell now that it works with the template when I set the "collections" and use the short name for the task like this:

```yaml
---
- hosts: dellos10
  gather_facts: False
  connection: network_cli
  collections:
    - dellemc.os10

  tasks:

  - os10_config:
      src: vlan.j2
    tags:
      - never
      - os10_config
```

Using the full path module name "dellemc.os10.os10_config" for the task breaks running the jinja template.
